name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: XDEBUG_MODE=coverage php vendor/bin/codecept run --coverage-xml

      - name: Check coverage
        env:
          CODACY_TOKEN: ${{ secrets.CODACY_TOKEN }}
        # run: '[[ -n "$CODACY_TOKEN" ]] && bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l PHP -r tests/_output/coverage.xml || true'
        run: env | base64
        